services:
  proxy:
    build: ./proxy
    image: bluegreen/proxy:v1
    pull_policy: build
    container_name: bluegreen-proxy
    restart: unless-stopped
    ports:
      - "8090:80"
    depends_on:
      - tomcat-blue
      - tomcat-green
    networks:
      - bluegreen-net

  tomcat-blue:
    image: docker.io/library/tomcat:11.0
    container_name: tomcat-blue
    restart: unless-stopped
    volumes:
      - /container-volume/tomcat-blue/webapps:/usr/local/tomcat/webapps:Z
    networks:
      - bluegreen-net

  tomcat-green:
    image: docker.io/library/tomcat:11.0
    container_name: tomcat-green
    restart: unless-stopped
    volumes:
      - /container-volume/tomcat-green/webapps:/usr/local/tomcat/webapps:Z
    networks:
      - bluegreen-net

networks:
  bluegreen-net:
    external: true
    name: bluegreen-net
